
CREATE OR REPLACE VIEW LOGISTICS_DB.PUBLIC.VW_LOGISTICS_DASHBOARD AS
SELECT SHIPMENT_TYPE,
    
COUNT(CASE WHEN ON_TIME = 1 THEN 1 END) AS SUCCESSFUL_DELIVERIES,
COUNT(SHIPMENT_ID) AS TOTAL_SHIPMENTS,
ROUND((COUNT(CASE WHEN ON_TIME = 1 THEN 1 END) / COUNT(SHIPMENT_ID)) * 100, 2) AS DELIVERY_SLA_ACCURACY_PCT,
    
ROUND(AVG(WEIGHT_KG), 2) AS AVG_SHIPMENT_WEIGHT_KG,
ROUND(AVG(DISTANCE_KM), 2) AS AVG_TRANSIT_DISTANCE_KM

FROM LOGISTICS_DB.PUBLIC.B
GROUP BY SHIPMENT_TYPE;

SELECT * FROM LOGISTICS_DB.PUBLIC.VW_LOGISTICS_DASHBOARD
ORDER BY DELIVERY_SLA_ACCURACY_PCT DESC;
